[config]
# will be set to mainnet by default if omitted
rpc = "https://fullnode.testnet.sui.io:443"

[packages]
LegatoMath = { local = "../../../core-contract/legato-math" }
# hasui_wrapper = { local = "../../../core-contract/hasui_wrapper" }
kamo = { local = "../../../core-contract/kamo" }
# haedal = { local = "../../../core-contract/haedal" }
kusdc_wrapper = { local = "../../../wrapper-contract/kusdc_wrapper" }
kusdc = { local = "../../../wrapper-contract/mock_kUSDC_testnet" }